# Rights declaration file
# For more information about syntax and structure see here:
# https://github.com/Splamy/TS3AudioBot/wiki/Rights

# Default rights for any client
"+" = [
	# Basic stuff
	"cmd.help.*",
	"cmd.pm",
	"cmd.kickme.*",
	"cmd.version",
	
	# Getting song info
	"cmd.song",
	"cmd.repeat",
	"cmd.random",

	# Conditionals and basic scripting
	"cmd.if",
	"cmd.print",
	"cmd.rng",
	"cmd.eval",
	"cmd.take",
	"cmd.xecute",
	"cmd.getmy.*",
	"cmd.json.*",
	"cmd.bot.use",
	"cmd.rights.can",

	# Bot avatar control
	"cmd.bot.avatar.*",
]

# Admin rule for localhost
[[rule]]
	ip = [ "127.0.0.1", "::1" ]
	"+" = "*"

# Admin rule for ServerAdmin group (group 6)
[[rule]]
	groupid = [ 6 ]
	"+" = "*"

# Playing rights for all server users
[[rule]]
	"+" = [
		# Play controls
		"cmd.play",
		"cmd.pause",
		"cmd.stop",
		"cmd.seek",
		"cmd.volume",
		"cmd.next",
		"cmd.previous",

		# Bot avatar
		"cmd.bot.avatar.*",

		# Search features
		"cmd.search.*",

		# Playlist management
		"cmd.list.*",
		"cmd.add",
		"cmd.clear",
		"cmd.random.*",
		"cmd.repeat.*",

		# History features
		"cmd.history.*",
		"cmd.alias.*"
	]
